[package]
name = "cc13x2"
version = "0.1.0"
authors = ["Robert Keith robert@helium.com"]

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
kernel = { path = "../../kernel" }
cc26xx = { path = "../../chips/cc26xx" }
bitfield = "0.13.0"
